package mywrk.dao.model;

// Generated Jul 13, 2017 2:08:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", schema = "mywrk")
public class Orders implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7896980499335892188L;
	private Long orderId;
	private Users users;
	private Date orderDttm;
	private Date requiredDate;
	private Boolean fulfilled;
	private Boolean paid;
	private Set<Orderlineitems> orderlineitemses = new HashSet<Orderlineitems>(
			0);

	public Orders() {
	}

	public Orders(Long orderId) {
		this.orderId = orderId;
	}

	public Orders(Long orderId, Users users, Date orderDttm, Date requiredDate,
			Boolean fulfilled, Boolean paid,
			Set<Orderlineitems> orderlineitemses) {
		this.orderId = orderId;
		this.users = users;
		this.orderDttm = orderDttm;
		this.requiredDate = requiredDate;
		this.fulfilled = fulfilled;
		this.paid = paid;
		this.orderlineitemses = orderlineitemses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "order_id", nullable = false)
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "related_user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_dttm", length = 29)
	public Date getOrderDttm() {
		return this.orderDttm;
	}

	public void setOrderDttm(Date orderDttm) {
		this.orderDttm = orderDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "required_date", length = 29)
	public Date getRequiredDate() {
		return this.requiredDate;
	}

	public void setRequiredDate(Date requiredDate) {
		this.requiredDate = requiredDate;
	}

	@Column(name = "fulfilled")
	public Boolean getFulfilled() {
		return this.fulfilled;
	}

	public void setFulfilled(Boolean fulfilled) {
		this.fulfilled = fulfilled;
	}

	@Column(name = "paid")
	public Boolean getPaid() {
		return this.paid;
	}

	public void setPaid(Boolean paid) {
		this.paid = paid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orders")
	public Set<Orderlineitems> getOrderlineitemses() {
		return this.orderlineitemses;
	}

	public void setOrderlineitemses(Set<Orderlineitems> orderlineitemses) {
		this.orderlineitemses = orderlineitemses;
	}

}
