package mywrk.dao.model;

// Generated Jul 13, 2017 2:08:22 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payments generated by hbm2java
 */
@Entity
@Table(name = "payments", schema = "mywrk")
public class Payments implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5463350676528784551L;
	private Long paymentId;
	private Invoices invoices;
	private Users users;
	private BigDecimal amountPaid;
	private Date paidOn;

	public Payments() {
	}

	public Payments(Long paymentId) {
		this.paymentId = paymentId;
	}

	public Payments(Long paymentId, Invoices invoices, Users users,
			BigDecimal amountPaid, Date paidOn) {
		this.paymentId = paymentId;
		this.invoices = invoices;
		this.users = users;
		this.amountPaid = amountPaid;
		this.paidOn = paidOn;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "payment_id", nullable = false)
	public Long getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Long paymentId) {
		this.paymentId = paymentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "related_invoice_id")
	public Invoices getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Invoices invoices) {
		this.invoices = invoices;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "related_user_id")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "amount_paid", precision = 10)
	public BigDecimal getAmountPaid() {
		return this.amountPaid;
	}

	public void setAmountPaid(BigDecimal amountPaid) {
		this.amountPaid = amountPaid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paid_on", length = 29)
	public Date getPaidOn() {
		return this.paidOn;
	}

	public void setPaidOn(Date paidOn) {
		this.paidOn = paidOn;
	}

}
