package mywrk.dao.model;

// Generated Jul 13, 2017 2:08:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkStatus generated by hbm2java
 */
@Entity
@Table(name = "work_status", schema = "mywrk")
public class WorkStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7858167680548159578L;
	private Long workStatusId;
	private Boolean fulfilled;
	private Date lastWorkedOn;
	private Set<Works> workses = new HashSet<Works>(0);

	public WorkStatus() {
	}

	public WorkStatus(Long workStatusId) {
		this.workStatusId = workStatusId;
	}

	public WorkStatus(Long workStatusId, Boolean fulfilled, Date lastWorkedOn,
			Set<Works> workses) {
		this.workStatusId = workStatusId;
		this.fulfilled = fulfilled;
		this.lastWorkedOn = lastWorkedOn;
		this.workses = workses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "work_status_id", nullable = false)
	public Long getWorkStatusId() {
		return this.workStatusId;
	}

	public void setWorkStatusId(Long workStatusId) {
		this.workStatusId = workStatusId;
	}

	@Column(name = "fulfilled")
	public Boolean getFulfilled() {
		return this.fulfilled;
	}

	public void setFulfilled(Boolean fulfilled) {
		this.fulfilled = fulfilled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_worked_on", length = 29)
	public Date getLastWorkedOn() {
		return this.lastWorkedOn;
	}

	public void setLastWorkedOn(Date lastWorkedOn) {
		this.lastWorkedOn = lastWorkedOn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workStatus")
	public Set<Works> getWorkses() {
		return this.workses;
	}

	public void setWorkses(Set<Works> workses) {
		this.workses = workses;
	}

}
