package mywrk.dao.model;

// Generated Jul 13, 2017 2:08:22 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkCategory generated by hbm2java
 */
@Entity
@Table(name = "work_category", schema = "mywrk")
public class WorkCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3695168652871560508L;
	private Long workCategoryId;
	private String categoryName;
	private String description;
	private Long createdBy;
	private Date creationDttm;
	private Set<Works> workses = new HashSet<Works>(0);

	public WorkCategory() {
	}

	public WorkCategory(Long workCategoryId) {
		this.workCategoryId = workCategoryId;
	}

	public WorkCategory(Long workCategoryId, String categoryName,
			String description, Long createdBy, Date creationDttm,
			Set<Works> workses) {
		this.workCategoryId = workCategoryId;
		this.categoryName = categoryName;
		this.description = description;
		this.createdBy = createdBy;
		this.creationDttm = creationDttm;
		this.workses = workses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "work_category_id", nullable = false)
	public Long getWorkCategoryId() {
		return this.workCategoryId;
	}

	public void setWorkCategoryId(Long workCategoryId) {
		this.workCategoryId = workCategoryId;
	}

	@Column(name = "category_name")
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "created_by")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_dttm", length = 29)
	public Date getCreationDttm() {
		return this.creationDttm;
	}

	public void setCreationDttm(Date creationDttm) {
		this.creationDttm = creationDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workCategory")
	public Set<Works> getWorkses() {
		return this.workses;
	}

	public void setWorkses(Set<Works> workses) {
		this.workses = workses;
	}

}
